version: '3.3'
services:
  logs-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'logs-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./db-script/createDb.sql:/docker-entrypoint-initdb.d/createDb.sql
    expose:
      - '3306'
volumes:
  logs-db:
